# Generated by Django 2.1.2 on 2019-05-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=2)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asig', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('Alumno_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rut_prof', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=2)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('Asignatura_id_asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.Asignatura')),
            ],
        ),
    ]
